#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calculadora.Resource", IsApplication=true)]

namespace Calculadora
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btn = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int btn0 = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int btn1 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int btn2 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btn3 = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int btn4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btn5 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btn6 = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int btn7 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btn8 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btn9 = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int btnDiminui = 2131034130;
			
			// aapt resource value: 0x7f050009
			public const int btnDivide = 2131034121;
			
			// aapt resource value: 0x7f05001a
			public const int btnIgual = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int btnInverte = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int btnLimpa = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int btnMultiplica = 2131034125;
			
			// aapt resource value: 0x7f050018
			public const int btnPonto = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int btnSoma = 2131034134;
			
			// aapt resource value: 0x7f050008
			public const int btn_ = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int tableLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int tableRow1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tableRow2 = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow3 = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int txtResultado = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
